on:
  workflow_dispatch:
    inputs:
      issue-title:
        description: 'Title of the issue'
        required: true
        default: 'Test issue'

jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: octo-sts/action@main
        id: octo-sts
        with:
          scope: test-organization-wwsean08/repo1
          identity: test
          domain: 'sts.wwsean08.com'

      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh issue create \
            --title "${{ github.event.inputs.issue-title }}" \
            --body "This is a test issue created by the workflow." \
            --repo test-organization-wwsean08/repo1